<a href="https://colab.research.google.com/github/devigorll/Curso-CD/blob/main/09_faca_voce_mesmo_tempo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

09. Este arquivo faz parte do desafio "Faça você mesmo" | O código abaixo é responsável por fazer a limpeza e tratamento de dados do arquivo "tempo.csv"

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

import pandas as pd
import statistics as sts
import seaborn as srn

In [ ]:
dataset = pd.read_csv("/content/drive/MyDrive/UDEMY/CURSO CD/04. LIMPEZA DE DADOS/tempo.csv", delimiter = ";")
dataset

In [ ]:
dataset.shape
dataset

In [ ]:
dataset.columns = ["APARENCIA", "TEMPERATURA", "UMIDADE", "VENTO", "JOGAR"]

dataset

   APARENCIA  TEMPERATURA  UMIDADE       VENTO JOGAR
0        sol           85     85.0       FALSO   nao
1        sol           80     90.0  VERDADEIRO   nao
2    nublado           83     86.0       FALSO   sim
3      chuva           70      NaN       FALSO   sim
4      chuva           68     80.0       FALSO   sim
5      chuva           65     70.0  VERDADEIRO   nao
6      menos           64     65.0  VERDADEIRO   sim
7        sol         1220     95.0       FALSO   nao
8        sol           69     70.0       FALSO   sim
9      chuva           75    200.0         NaN   sim
10       sol           75     70.0  VERDADEIRO   sim
11   nublado           72     90.0  VERDADEIRO   sim
12   nublado           81     75.0       FALSO   sim
13     chuva           71     91.0  VERDADEIRO   nao

In [ ]:
dataset.loc[dataset["TEMPERATURA"] > 100]

dataset.loc[dataset["TEMPERATURA"] > 100, "TEMPERATURA"] = mediana_temperatura

Empty DataFrame
Columns: [APARENCIA, TEMPERATURA, UMIDADE, VENTO, JOGAR]
Index: []

In [ ]:
mediana_temperatura = sts.median(dataset["TEMPERATURA"])
mediana_temperatura

73.5

In [ ]:
dataset

   APARENCIA  TEMPERATURA  UMIDADE       VENTO JOGAR
0        sol         85.0     85.0       FALSO   nao
1        sol         80.0     90.0  VERDADEIRO   nao
2    nublado         83.0     86.0       FALSO   sim
3      chuva         70.0      NaN       FALSO   sim
4      chuva         68.0     80.0       FALSO   sim
5      chuva         65.0     70.0  VERDADEIRO   nao
6      menos         64.0     65.0  VERDADEIRO   sim
7        sol         73.5     95.0       FALSO   nao
8        sol         69.0     70.0       FALSO   sim
9      chuva         75.0    200.0         NaN   sim
10       sol         75.0     70.0  VERDADEIRO   sim
11   nublado         72.0     90.0  VERDADEIRO   sim
12   nublado         81.0     75.0       FALSO   sim
13     chuva         71.0     91.0  VERDADEIRO   nao

In [ ]:
mediana_umidade = sts.median(dataset["UMIDADE"])
mediana_umidade

85.5

In [ ]:
dataset.loc[dataset["UMIDADE"] > 100, "UMIDADE"] = mediana_umidade
dataset

   APARENCIA  TEMPERATURA  UMIDADE       VENTO JOGAR
0        sol         85.0     85.0       FALSO   nao
1        sol         80.0     90.0  VERDADEIRO   nao
2    nublado         83.0     86.0       FALSO   sim
3      chuva         70.0      NaN       FALSO   sim
4      chuva         68.0     80.0       FALSO   sim
5      chuva         65.0     70.0  VERDADEIRO   nao
6      menos         64.0     65.0  VERDADEIRO   sim
7        sol         73.5     95.0       FALSO   nao
8        sol         69.0     70.0       FALSO   sim
9      chuva         75.0     85.5         NaN   sim
10       sol         75.0     70.0  VERDADEIRO   sim
11   nublado         72.0     90.0  VERDADEIRO   sim
12   nublado         81.0     75.0       FALSO   sim
13     chuva         71.0     91.0  VERDADEIRO   nao

In [ ]:
dataset.loc[dataset["VENTO"].isnull(), "VENTO"] = "FALSO"

dataset

agrupado = dataset.groupby(["VENTO"]).size()
agrupado

VENTO
FALSO         8
VERDADEIRO    6
dtype: int64

In [ ]:
dataset

   APARENCIA  TEMPERATURA  UMIDADE       VENTO JOGAR
0        sol         85.0     85.0       FALSO   nao
1        sol         80.0     90.0  VERDADEIRO   nao
2    nublado         83.0     86.0       FALSO   sim
3      chuva         70.0      NaN       FALSO   sim
4      chuva         68.0     80.0       FALSO   sim
5      chuva         65.0     70.0  VERDADEIRO   nao
6      menos         64.0     65.0  VERDADEIRO   sim
7        sol         73.5     95.0       FALSO   nao
8        sol         69.0     70.0       FALSO   sim
9      chuva         75.0     85.5       FALSO   sim
10       sol         75.0     70.0  VERDADEIRO   sim
11   nublado         72.0     90.0  VERDADEIRO   sim
12   nublado         81.0     75.0       FALSO   sim
13     chuva         71.0     91.0  VERDADEIRO   nao

In [ ]:
agrupado = dataset.groupby(["APARENCIA"]).size()
agrupado

dataset.drop

APARENCIA
chuva      5
menos      1
nublado    3
sol        5
dtype: int64